targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/model/state.dart
            - lib/model/data/class.dart
            - lib/model/data/config.dart

      json_serializable:
        generate_for:
          include:
            - lib/model/state.dart
            - lib/model/data/class.dart
            - lib/model/data/config.dart

        options:
          any_map: true
          explicit_to_json: true
